### PR TITLE
Node installaton guide

### PR DESCRIPTION
**Pull request by LeonoorsCryptoman**
Outline how to set up a node on the Arkeo network.

note that a couple of things are missing:
- binary version to be installed
- location of the genesis file
- seeds
- binary name

### CODE REVIEW

**Comment by 0xean** [comment]
@LeonoorsCryptoman - thanks for the PR - any reason to not merge this with the existing readme and not keep the old readme?

**Comment by LeonoorsCryptoman** [comment]
> @LeonoorsCryptoman - thanks for the PR - any reason to not merge this with the existing readme and not keep the old readme?

I was not sure if you would still need / want the old file. Now you have control whether to keep or delete the file :)

**Comment by LeonoorsCryptoman** [comment]
Is it desired to merge it into 1 file?

Not sure if the content of readme_old is worth saving though, but I'll leave that decision to you guys ^^

**Comment by 0xean** [comment]
thanks @LeonoorsCryptoman - would be good to keep some of what exists in there, but agree most of its boilerplate and not needed.

**Comment by LeonoorsCryptoman** [comment]
> thanks @LeonoorsCryptoman - would be good to keep some of what exists in there, but agree most of its boilerplate and not needed.

So, best to merge the files?

If yes, then I'll create an update for it :)

**Comment by 0xean** [comment]
that would be great! thanks @LeonoorsCryptoman

**Comment by LeonoorsCryptoman** [comment]
I'll create a new pull request with the applicable change :)

**Pull request closed without merging**
