### PR TITLE
Add script to setup validator

### PR DESCRIPTION
**Pull request by johnnyluo**
This PR add validator.sh, which setup a node as full node , and can be bond to become a validator

Also add `arkeod-1` into docker compose file , so when using docker compose , it will automatically setup genesis node , and also a validator ready to bond up

### CODE REVIEW

**Comment by LeonoorsCryptoman** [comment]
Will you also add a guide to how to create a node?
I always prefer manual setup, since it offers a bit more control over the inner workings.

If you like, I can create that guide in a README.md file to be included on Github

**Review by 0xean — CHANGES_REQUESTED** [review]

**Comment by johnnyluo** [comment]
> Will you also add a guide to how to create a node? I always prefer manual setup, since it offers a bit more control over the inner workings.
> 
> If you like, I can create that guide in a README.md file to be included on Github

go ahead and raise a PR.

**Comment by 0xean** [comment]
Looks like the linter is complaining

**Comment by LeonoorsCryptoman** [comment]
> > Will you also add a guide to how to create a node? I always prefer manual setup, since it offers a bit more control over the inner workings.
> > If you like, I can create that guide in a README.md file to be included on Github
> 
> go ahead and raise a PR.

Pull request opened
https://github.com/arkeonetwork/arkeo/pull/53

**Review by 0xean — APPROVED** [review]

**Pull request merged**
